import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input_linked_file", help="original linked phrase file generated by wikiLinker")
    parser.add_argument("output_keywords_file", help="output keywords file")
    args = parser.parse_args()

    filepath = args.input_linked_file
    output_filepath = args.output_keywords_file


    with open(filepath) as f:
        data = [i for i in f]

    data = data[1:]
    phrase_cnt = 0
    phrase_list = []
    for d in data:
        phrase, combined_score, _  = d.split('\t', 2)
        score = float(combined_score)
        if score >= 1.0:
            phrase_list.append(phrase)
            phrase_cnt += 1


    print('#%d phrases'%phrase_cnt)
    with open(output_filepath, 'w') as fout:
        for phrase in phrase_list:
            fout.write(phrase + '\n')

if __name__ == '__main__':
    main()

